version: '3.8'

services:

  vault:
    image: library/vault:1.12.2
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: vault_config.json
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    cap_add:
      - IPC_LOCK
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault_config.json
